#!/bin/bash
#
# backup: Backup files in $HOME to /mnt
#

sudo cryptsetup luksOpen /dev/sdb1 backup && \
sudo mount /dev/mapper/backup /mnt && \
rsync --archive --delete --exclude=.cookies/ --verbose ${HOME} /mnt && \
sudo umount /mnt && \
sudo cryptsetup luksClose backup && \
echo Operation succeeded! && exit 0

echo Operation failed! && exit 1
