#!/bin/bash
#
# dupes: Find duplicate files according to md5sum
#

if [[ ${#} -ne 1 || ! -d ${1} ]]; then
  echo Usage: dupes PATH >&2
  exit 1
fi

find "${1}" -type f | \

while read FILE; do
  stat -c"%16s%n" "${FILE}"
done | sort -n | uniq -Dw16 | cut -c17- | \

while read FILE; do
  md5sum "${FILE}"
done | sort -n | uniq -Dw32

exit 0
