#!/bin/bash
#
# paccheck: Give an overview of important package info
#

GROUPLIST="base base-devel"

print () {
  tee >([[ $(wc -l) -eq 0 ]] && echo "(none)") \
      | while read LINE; do echo "==> ${LINE}"; done
}


echo "Packages not installed from server groups"
comm -23 <(pacman -Sqg ${GROUPLIST} | sort -u) \
         <(pacman -Qq | sort) | print

echo

echo "Packages not required by other packages"
pacman -Qdt | print

echo

echo "Packages explicitly installed"
  if [[ "${1}" == "-v" ]]; then
    comm -23 <(pacman -Qqe | sort) \
             <(pacman -Qqg ${GROUPLIST} | sort)
  else
    echo use -v to view
  fi | print

echo

echo "Modified config files"
pacman -Qii | awk '/^MODIFIED/ { print $2 }' | sort | print

exit 0
