#!/bin/bash
#
# purge: Purge unwanted files with confirmation
#

source ${0%/*}/utils/config || exit 1

u () { echo -e "\033[4m${@}\033[0m"; }

IFS=$'\n'; for FILE in ${PURGE_FILES}; do
  [[ -a "${FILE}" ]] || continue
  read -p "Remove $(u ${FILE}) [y/N]? "
  [[ ${REPLY} == y ]] && rm -rf "${FILE}"
done

exit 0
