#!/bin/bash
#
# qiv-command: Command file for use with the Quick Image Viewer
#

case "${1}" in
  0|1|2|3|4|5|6|7|8|9) mkdir -p ${1} && \
                       mv -f "${2}" ${1} ;;
  *) echo "Unrecognized command" >&2; exit 1 ;;
esac

exit 0
